// fronted dev web UI/src/lib/components/ui/SectionHeader.svelte
<script lang="ts">
  export let title = ''
  export let subtitle = ''
</script>

<div style="display:flex;justify-content:space-between;align-items:flex-start;gap:0.75rem;">
  <div>
    <h2 style="margin:0;font-size:1rem;">{title}</h2>
    {#if subtitle}
      <p style="margin:0.2rem 0 0 0;color:var(--ink-500);font-size:0.85rem;">{subtitle}</p>
    {/if}
  </div>
  <div>
    <slot name="actions" />
  </div>
</div>

// fronted dev web UI/src/components/ui/SectionHeader.tsx
import type { PropsWithChildren, ReactNode } from 'react'

type SectionHeaderProps = PropsWithChildren<{
  title: string
  subtitle?: string
  actions?: ReactNode
}>

export const SectionHeader = ({ title, subtitle, actions }: SectionHeaderProps) => (
  <header className="flex flex-wrap items-start justify-between gap-3">
    <div>
      <h2 className="text-2xl font-semibold text-[var(--ink-900)]">{title}</h2>
      {subtitle ? <p className="mt-1 text-sm text-[var(--ink-500)]">{subtitle}</p> : null}
    </div>
    {actions ? <div className="flex flex-wrap items-center gap-2">{actions}</div> : null}
  </header>
)
